# -*- coding: utf-8 -*-
"""naive-bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lbqkDb-3TQn4xKu3yUzMeS8tjgZLwd4k
"""

import numpy as np
import pandas as pd

df = pd.read_csv('https://gist.githubusercontent.com/DiogoRibeiro7/c6590d0cf119e87c39e31c21a9c0f3a8/raw/4a8e3da267a0c1f0d650901d8295a5153bde8b21/PlayTennis.csv')

df

pd.crosstab(df['Outlook'], df['Play Tennis'],normalize='columns').stack().to_dict()

D = {}
for i in ['Outlook','Temperature',	'Humidity',	'Wind']:
  D.update(pd.crosstab(df[i], df['Play Tennis'],normalize='columns').stack().to_dict())

D

